### ISSUE TITLE
semantic-release-backmerge not working from v1.4.1 with GitHub Actions.

### ISSUE THREAD

**Issue by kkoudev** [saitho/semantic-release-backmerge#15]
Hello.
semantic-release-backmerge not working from v1.4.1 with GitHub Actions.
The v1.4.0 works fine with same config.

My config this:

```
  "release": {
    "plugins": [
      "@semantic-release/commit-analyzer",
      "@semantic-release/release-notes-generator",
      "@semantic-release/npm",
      [
        "@semantic-release/exec",
        {
          "prepareCmd": "cat package.json | jq -r '.version'"
        }
      ],
      "@semantic-release/github",
      [
        "@semantic-release/git",
        {
          "assets": [
            "dist/**/*.{js,css}",
            "docs",
            "package.json"
          ],
          "message": "chore(release): ${nextRelease.version} \n\n${nextRelease.notes}"
        }
      ],
      [
        "@saithodev/semantic-release-backmerge",
        {
          "branchName": "develop",
          "plugins": [
            [
              "@semantic-release/exec",
              {
                "successCmd": "echo 'Latest release version is ${nextRelease.version}' > release-version.txt && git add release-version.txt"
              }
            ]
          ]
        }
      ]
    ]
  }
```

GitHub Actions workflow:

```yaml
name: Release

on:
  push:
    # branches to consider in the event; optional, defaults to all
    # master
    branches:
      - master

jobs:
  semantic_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        with:
          # You can specify specifying version range for the extra plugins if you prefer.
          extra_plugins: |
            @semantic-release/commit-analyzer
            @semantic-release/release-notes-generator
            @semantic-release/npm
            @semantic-release/exec
            @semantic-release/github
            @semantic-release/git
            @saithodev/semantic-release-backmerge
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

GitHub Actions error logs:

```
[1:09:32 PM] [semantic-release] › ℹ  Start step "success" of plugin "@saithodev/semantic-release-backmerge"
[1:09:32 PM] [semantic-release] [@saithodev/semantic-release-backmerge] › ℹ  Release succeeded. Performing back-merge into branch "develop".
[1:09:32 PM] [semantic-release] › ✖  Failed step "success" of plugin "@saithodev/semantic-release-backmerge"
[1:09:32 PM] [semantic-release] › ✖  An error occurred while running semantic-release: Error: Command failed with exit code 1: git checkout develop
error: pathspec 'develop' did not match any file(s) known to git
Error: AggregateError: 
    Error: Command failed with exit code 1: git checkout develop
    error: pathspec 'develop' did not match any file(s) known to git
        at makeError (/home/runner/work/_actions/cycjimmy/semantic-release-action/v2/node_modules/execa/lib/error.js:59:11)
        at handlePromise (/home/runner/work/_actions/cycjimmy/semantic-release-action/v2/node_modules/execa/index.js:114:26)
    at makeError (/home/runner/work/_actions/cycjimmy/semantic-release-action/v2/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/home/runner/work/_actions/cycjimmy/semantic-release-action/v2/node_modules/execa/index.js:114:26)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  shortMessage: 'Command failed with exit code 1: git checkout develop',
  command: 'git checkout develop',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: "error: pathspec 'develop' did not match any file(s) known to git",
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false,
  pluginName: '@saithodev/semantic-release-backmerge'
}
```

It looks like git checkout is failing.
It need to add some configs from v1.4.1?
Thank you.
