### ISSUE TITLE
Backmerge on feature branches

### ISSUE THREAD

**Issue by mehdihadeli** [saitho/semantic-release-backmerge#42]
Hi,
Is it possible back merge develop branch on feature branches? 
Because naming for branches doesn't support `regex` (like: feat/**), we can't do this now.
For example:
``` yaml
- - '@saithodev/semantic-release-backmerge'
  - branches:
    - from: main
      to: dev
    - from: dev
      to: feat/**
    backmergeStrategy: merge
    mergeMode: ours 
    clearWorkspace: false
```
