### ISSUE TITLE
<title>

### ISSUE THREAD

**Issue by jhlmco** [saitho/semantic-release-backmerge#51]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Creating a new branch `develop` and ignoring configuration.  I do not 

Configuration:

```yaml
  - - "@saithodev/semantic-release-backmerge"
    - backmergeBranches:
      - dev
      - from: dev
        to: next
```

Note have also tried the following with the same results:

```yaml
  - - "@saithodev/semantic-release-backmerge"
    - backmergeBranches:
      - from: main
        to: dev
      - from: dev
        to: next
```

Logs:

```bash
[8:22:42 PM] [semantic-release] › ℹ  Start step "success" of plugin "@saithodev/semantic-release-backmerge"
[8:22:42 PM] [semantic-release] [@saithodev/semantic-release-backmerge] › ℹ  Fetching all remotes.
[8:22:42 PM] [semantic-release] [@saithodev/semantic-release-backmerge] › ℹ  Fetching latest commits from repository at "[https://[secure]@gitlab.com/hoppr/hoppr.git](https://%5Bsecure%5D@gitlab.com/hoppr/hoppr.git)".
[8:22:43 PM] [semantic-release] [@saithodev/semantic-release-backmerge] › ℹ  Performing back-merge into develop branch "develop".
[8:22:43 PM] [semantic-release] [@saithodev/semantic-release-backmerge] › ℹ  Branch is detached. Checking out release branch "dev".
[8:22:43 PM] [semantic-release] [@saithodev/semantic-release-backmerge] › ℹ  Checking out develop branch "develop".
[8:22:43 PM] [semantic-release] [@saithodev/semantic-release-backmerge] › ℹ  Performing backmerge with "rebase" strategy.
[8:22:43 PM] [semantic-release] [@saithodev/semantic-release-backmerge] › ℹ  Loading plugins
[8:22:43 PM] [semantic-release] [@saithodev/semantic-release-backmerge] › ℹ  Executing "done" step of plugins
[8:22:43 PM] [semantic-release] [@saithodev/semantic-release-backmerge] › ℹ  Found 0 staged files for back-merge commit
[8:22:43 PM] [semantic-release] [@saithodev/semantic-release-backmerge] › ℹ  Pushing backmerge to develop branch develop
[8:22:44 PM] [semantic-release] › ✔  Completed step "success" of plugin "@saithodev/semantic-release-backmerge"
[8:22:44 PM] [semantic-release] › ✔  Published release 1.8.5-dev.13 on dev channel
```

### Expected Behavior

Back merge from: main -> dev and dev -> next

### Steps To Reproduce

Link to config:

https://gitlab.com/hoppr/hoppr/-/blob/dev/.releaserc.yml#L71

### Environment

```markdown
- **semantic-release/semantic-release** version: "21.0.5"
- **@saithodev/semantic-release-backmerge** version: "3.2.0"
```
